<?php

function docassemble_embed_library_info_alter(&$libraries, $extension) {
    if ($extension == 'docassemble_embed'){
        $config = \Drupal::config('docassemble_embed.settings');
        $url = rtrim(trim($config->get('docassemble_embed.server')), '/');
        $bootstrap = trim($config->get('docassemble_embed.bootstrap'));
        $css = array();
        $js = array();
        $external = array('type' => 'external');
        if ($bootstrap != ''){
            if (substr($bootstrap, 0, 1) == '/'){
                $css[$url . $bootstrap] = $external;
            }
            else{
                $css[$bootstrap] = $external;
            }
        }
        $css[$url . '/static/app/bundle.css'] = $external;
        $js[$url . '/static/app/bundlenojquery.js'] = $external;
        $libraries['docassemble-assets']['css'] = array('theme' => $css);
        $libraries['docassemble-assets']['js'] = $js;
    }
}